In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
import ast
from scipy.sparse import csr_matrix

In [2]:
output_path = "../input/"
train_path = output_path + "train/"
val_path = output_path + "val/"

train_df = train_path + "train_data_split.csv"
val_df = val_path + "val_data_split.csv"
train_emb = train_path + "train_embeddings_split.npy"
val_emb = val_path + "val_embeddings_split.npy"

y_train_sparse_path = train_path + "Y_train_sparse.npy"
y_val_sparse_path = val_path + "Y_val_sparse.npy"

classes_path = output_path + "classes.npy"
ia_weights_path = "../../general_input/IA.tsv"
final_ia_weights_path = output_path + "ia_weights.npy"

In [3]:
df_train = pd.read_csv(train_df)
df_val = pd.read_csv(val_df)
X_train = np.load(train_emb)
X_val = np.load(val_emb)

In [4]:
def safe_eval_and_flatten(x):
    if pd.notna(x) and x.strip().startswith('['):
        try:
            # 1. Convert string to list of lists (e.g., "[['GO:1'], ['GO:2', 'GO:3']]")
            evaluated_list_of_lists = ast.literal_eval(x)
            
            # 2. Flatten the list of lists into a single list
            return [term for sublist in evaluated_list_of_lists for term in sublist]
        except:
            # Return empty list if evaluation fails
            return []
    return []

def parse_go_terms_flattened(go_terms_series):
    # Apply the safe evaluation and flattening function to the series
    return go_terms_series.apply(safe_eval_and_flatten)

In [5]:
df_train

,db,id,name,full_name,organism,taxon,gen,PE,SV,sequence,length,go_terms,aspect
0,sp,A0A023FT45,EV985_AMBPA,Evasin P985,Amblyomma parvum,251391,NaN,2,1,MHSTIAYVSLLPLALFVAMHGASTDEESEELGASTDVDYEELDANC...,132,[['GO:0019957']],['F']
1,sp,A0A023G6B6,E1180_AMBTT,Evasin P1180,Amblyomma triste,251400,NaN,3,2,MARNWSFRVIFVSAMWCALLKFATLEEPKDGYDYTEGCPFVVLGNG...,116,[['GO:0019957']],['F']
2,sp,A0A023G9N9,E1183_AMBTT,Evasin P1183,Amblyomma triste,251400,NaN,3,2,MTRNWSFRVIFVSAMWCALLKFATLEAPKDDFEYDGGCPFVVLDNG...,115,[['GO:0019957']],['F']
3,sp,A0A023I7E1,ENG1_RHIMI,"Glucan endo-1,3-beta-D-glucosidase 1",Rhizomucor miehei,4839,ENG1,1,1,MRFQVIVAAATITMITSYIPGVASQSTSDGDDLFVPVSNFDPKSIF...,796,"[['GO:0042973'], ['GO:0000272']]","['F', 'P']"
4,sp,A0A023PXP4,YL235_YEAST,Putative uncharacterized protein YLR235C,Saccharomyces cerevisiae (strain ATCC 204508 /...,559292,YLR235C,5,1,MLIGAPSNMRLRGALELLWRRLLHGLMQLRLVLKMHICSQLNHAIK...,132,[['GO:0006974']],['P']
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58356,sp,X2JDY8,RHGF_DROME,Rho GTPase-activating protein Graf,Drosophila melanogaster,7227,Graf,1,1,MGGGKNVRRGLEPLEFEECIVDSPDFRENLNRHEKELDHTSHQIKR...,1025,"[['GO:0140036'], ['GO:0031410'], ['GO:0002092'...","['F', 'C', 'P', 'P', 'C', 'C', 'C', 'F', 'P', ..."
58357,sp,X4Y2L4,LHYAL_HIRNI,Hyaluronoglucuronidase,Hirudo nipponia,42736,NaN,1,1,MKEIAVTIDDKNVIASVSESFHGVAFDASLFSPKGLWSFVDITSPK...,489,"[['GO:0033906'], ['GO:0030214']]","['F', 'P']"
58358,sp,X5JA13,SECAA_ARATH,Exocyst complex component SEC10a,Arabidopsis thaliana,3702,SEC10a,1,1,MTEGIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,825,"[['GO:0070062'], ['GO:0005829'], ['GO:0005515'...","['C', 'C', 'F', 'C', 'C', 'C', 'C', 'P']"
58359,sp,X5JB51,SECAB_ARATH,Exocyst complex component SEC10b,Arabidopsis thaliana,3702,SEC10b,1,1,MTERIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,829,"[['GO:0070062'], ['GO:0005829'], ['GO:0005886'...","['C', 'C', 'C', 'C', 'C', 'C', 'P', 'F']"
58360,sp,X5M5N0,WNK_CAEEL,Serine/threonine-protein kinase WNK,Caenorhabditis elegans,6239,wnk-1,1,1,MPDSITNGGRPPAPPSSVSSTTASTTGNFGTRRRLVNRIKKVDELH...,1850,"[['GO:0140693'], ['GO:0140694'], ['GO:0006884'...","['F', 'P', 'P', 'P', 'F', 'P', 'P', 'P']"

In [6]:
y_train_lists = parse_go_terms_flattened(df_train['go_terms'])
y_val_lists = parse_go_terms_flattened(df_val['go_terms'])

In [7]:
# Binarizer
mlb = MultiLabelBinarizer(sparse_output=True)

In [8]:
# Codification adjustment
Y_train_sparse = mlb.fit_transform(y_train_lists)

In [9]:
Y_val_sparse = mlb.transform(y_val_lists)

/home/maria/miniconda3/envs/torch_env_kaggle_wi/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['GO:0000048', 'GO:0000098', 'GO:0000099', 'GO:0000109', 'GO:0000270', 'GO:0000308', 'GO:0000430', 'GO:0000438', 'GO:0000716', 'GO:0000832', 'GO:0000835', 'GO:0000962', 'GO:0001000', 'GO:0001067', 'GO:0001070', 'GO:0001072', 'GO:0001117', 'GO:0001172', 'GO:0001512', 'GO:0001572', 'GO:0001586', 'GO:0001587', 'GO:0001607', 'GO:0001681', 'GO:0001695', 'GO:0001770', 'GO:0001790', 'GO:0001792', 'GO:0001814', 'GO:0001815', 'GO:0001847', 'GO:0001855', 'GO:0001861', 'GO:0001882', 'GO:0001884', 'GO:0001910', 'GO:0001918', 'GO:0002097', 'GO:0002101', 'GO:0002132', 'GO:0002136', 'GO:0002153', 'GO:0002172', 'GO:0002178', 'GO:0002190', 'GO:0002191', 'GO:0002193', 'GO:0002220', 'GO:0002222', 'GO:0002228', 'GO:0002252', 'GO:0002263', 'GO:0002264', 'GO:0002266', 'GO:0002274', 'GO:0002295', 'GO:0002312', 'GO:0002384', 'GO:0002398', 'GO:0002399', 'GO:0002419', 'GO:0002429', 'GO:0002435', 'GO:0002436', 'GO:0002450', 'GO:0002451', 'GO:0002461', 'GO:0002469', 'GO:0002470', 'GO:0002477', 'GO:0002480', 'GO:0002486', 'GO:0002491', 'GO:0002503', 'GO:0002504', 'GO:0002509', 'GO:0002519', 'GO:0002528', 'GO:0002541', 'GO:0002562', 'GO:0002575', 'GO:0002578', 'GO:0002581', 'GO:0002587', 'GO:0002590', 'GO:0002622', 'GO:0002625', 'GO:0002645', 'GO:0002664', 'GO:0002676', 'GO:0002684', 'GO:0002715', 'GO:0002721', 'GO:0002737', 'GO:0002747', 'GO:0002765', 'GO:0002767', 'GO:0002812', 'GO:0002834', 'GO:0002854', 'GO:0002935', 'GO:0002937', 'GO:0002938', 'GO:0002943', 'GO:0002944', 'GO:0002945', 'GO:0002947', 'GO:0002952', 'GO:0003058', 'GO:0003064', 'GO:0003092', 'GO:0003095', 'GO:0003099', 'GO:0003131', 'GO:0003133', 'GO:0003146', 'GO:0003173', 'GO:0003187', 'GO:0003189', 'GO:0003206', 'GO:0003221', 'GO:0003261', 'GO:0003262', 'GO:0003285', 'GO:0003305', 'GO:0003308', 'GO:0003313', 'GO:0003314', 'GO:0003317', 'GO:0003318', 'GO:0003324', 'GO:0003330', 'GO:0003355', 'GO:0003359', 'GO:0003363', 'GO:0003366', 'GO:0003370', 'GO:0003421', 'GO:0003428', 'GO:0003880', 'GO:0003920', 'GO:0003943', 'GO:0003944', 'GO:0003957', 'GO:0003963', 'GO:0003976', 'GO:0004071', 'GO:0004119', 'GO:0004125', 'GO:0004139', 'GO:0004159', 'GO:0004355', 'GO:0004361', 'GO:0004376', 'GO:0004456', 'GO:0004492', 'GO:0004493', 'GO:0004522', 'GO:0004561', 'GO:0004569', 'GO:0004787', 'GO:0004808', 'GO:0004821', 'GO:0004877', 'GO:0004906', 'GO:0004909', 'GO:0004912', 'GO:0004913', 'GO:0004914', 'GO:0004917', 'GO:0004939', 'GO:0004961', 'GO:0004978', 'GO:0004979', 'GO:0004992', 'GO:0005019', 'GO:0005115', 'GO:0005129', 'GO:0005133', 'GO:0005139', 'GO:0005151', 'GO:0005152', 'GO:0005153', 'GO:0005171', 'GO:0005217', 'GO:0005260', 'GO:0005289', 'GO:0005292', 'GO:0005294', 'GO:0005307', 'GO:0005477', 'GO:0005579', 'GO:0005582', 'GO:0005590', 'GO:0005591', 'GO:0005592', 'GO:0005594', 'GO:0005597', 'GO:0005599', 'GO:0005600', 'GO:0005601', 'GO:0005607', 'GO:0005690', 'GO:0005691', 'GO:0005889', 'GO:0005893', 'GO:0005898', 'GO:0005900', 'GO:0005943', 'GO:0005984', 'GO:0006053', 'GO:0006115', 'GO:0006173', 'GO:0006185', 'GO:0006209', 'GO:0006214', 'GO:0006229', 'GO:0006253', 'GO:0006254', 'GO:0006475', 'GO:0006477', 'GO:0006478', 'GO:0006480', 'GO:0006481', 'GO:0006482', 'GO:0006501', 'GO:0006517', 'GO:0006577', 'GO:0006677', 'GO:0006692', 'GO:0006738', 'GO:0006761', 'GO:0006766', 'GO:0006787', 'GO:0006862', 'GO:0007171', 'GO:0007172', 'GO:0007252', 'GO:0007258', 'GO:0007260', 'GO:0007275', 'GO:0007321', 'GO:0007387', 'GO:0007597', 'GO:0008127', 'GO:0008169', 'GO:0008172', 'GO:0008192', 'GO:0008263', 'GO:0008269', 'GO:0008309', 'GO:0008389', 'GO:0008448', 'GO:0008456', 'GO:0008490', 'GO:0008493', 'GO:0008513', 'GO:0008532', 'GO:0008591', 'GO:0008607', 'GO:0008617', 'GO:0008626', 'GO:0008662', 'GO:0008664', 'GO:0008667', 'GO:0008668', 'GO:0008671', 'GO:0008672', 'GO:0008673', 'GO:0008674', 'GO:0008675', 'GO:0008679', 'GO:0008681', 'GO:0008682', 'GO:0008684', 'GO:0008688', 'GO:0008692', 'GO:0008694', 'GO:0008697', 'GO:0008701', 'GO:0008706', 'GO:0008709', 'GO:0008712', 'GO:0008713', 'GO:0008714', 'GO:0008715', 'GO:0008719', 'GO:0008726', 'GO:0008727', 'GO:0008733', 'GO:0008734', 'GO:0008735', 'GO:0008736', 'GO:0008737', 'GO:0008740', 'GO:0008741', 'GO:0008742', 'GO:0008744', 'GO:0008748', 'GO:0008750', 'GO:0008752', 'GO:0008753', 'GO:0008760', 'GO:0008762', 'GO:0008764', 'GO:0008766', 'GO:0008770', 'GO:0008771', 'GO:0008772', 'GO:0008779', 'GO:0008782', 'GO:0008785', 'GO:0008786', 'GO:0008787', 'GO:0008788', 'GO:0008790', 'GO:0008795', 'GO:0008797', 'GO:0008798', 'GO:0008801', 'GO:0008803', 'GO:0008808', 'GO:0008809', 'GO:0008811', 'GO:0008829', 'GO:0008838', 'GO:0008849', 'GO:0008854', 'GO:0008855', 'GO:0008861', 'GO:0008864', 'GO:0008866', 'GO:0008868', 'GO:0008870', 'GO:0008872', 'GO:0008873', 'GO:0008874', 'GO:0008876', 'GO:0008877', 'GO:0008884', 'GO:0008890', 'GO:0008899', 'GO:0008903', 'GO:0008912', 'GO:0008914', 'GO:0008919', 'GO:0008920', 'GO:0008923', 'GO:0008925', 'GO:0008927', 'GO:0008932', 'GO:0008933', 'GO:0008937', 'GO:0008949', 'GO:0008951', 'GO:0008955', 'GO:0008959', 'GO:0008960', 'GO:0008961', 'GO:0008963', 'GO:0008965', 'GO:0008968', 'GO:0008979', 'GO:0008983', 'GO:0008984', 'GO:0008986', 'GO:0008990', 'GO:0008993', 'GO:0008994', 'GO:0008995', 'GO:0008998', 'GO:0008999', 'GO:0009014', 'GO:0009015', 'GO:0009016', 'GO:0009017', 'GO:0009022', 'GO:0009024', 'GO:0009025', 'GO:0009026', 'GO:0009027', 'GO:0009028', 'GO:0009030', 'GO:0009034', 'GO:0009036', 'GO:0009037', 'GO:0009040', 'GO:0009042', 'GO:0009045', 'GO:0009046', 'GO:0009050', 'GO:0009059', 'GO:0009064', 'GO:0009066', 'GO:0009104', 'GO:0009151', 'GO:0009154', 'GO:0009156', 'GO:0009168', 'GO:0009188', 'GO:0009223', 'GO:0009239', 'GO:0009242', 'GO:0009246', 'GO:0009255', 'GO:0009271', 'GO:0009290', 'GO:0009291', 'GO:0009295', 'GO:0009304', 'GO:0009307', 'GO:0009309', 'GO:0009316', 'GO:0009318', 'GO:0009319', 'GO:0009321', 'GO:0009325', 'GO:0009326', 'GO:0009329', 'GO:0009331', 'GO:0009333', 'GO:0009338', 'GO:0009341', 'GO:0009342', 'GO:0009345', 'GO:0009346', 'GO:0009347', 'GO:0009355', 'GO:0009356', 'GO:0009360', 'GO:0009366', 'GO:0009368', 'GO:0009376', 'GO:0009379', 'GO:0009380', 'GO:0009382', 'GO:0009389', 'GO:0009390', 'GO:0009392', 'GO:0009401', 'GO:0009419', 'GO:0009424', 'GO:0009426', 'GO:0009428', 'GO:0009431', 'GO:0009441', 'GO:0009486', 'GO:0009582', 'GO:0009665', 'GO:0009675', 'GO:0009692', 'GO:0009756', 'GO:0009803', 'GO:0009822', 'GO:0009841', 'GO:0009895', 'GO:0009995', 'GO:0010138', 'GO:0010139', 'GO:0010348', 'GO:0010456', 'GO:0010465', 'GO:0010518', 'GO:0010573', 'GO:0010610', 'GO:0010707', 'GO:0010710', 'GO:0010711', 'GO:0010727', 'GO:0010748', 'GO:0010752', 'GO:0010770', 'GO:0010814', 'GO:0010816', 'GO:0010819', 'GO:0010879', 'GO:0010900', 'GO:0010905', 'GO:0010908', 'GO:0010909', 'GO:0010916', 'GO:0010922', 'GO:0010923', 'GO:0010948', 'GO:0010949', 'GO:0010952', 'GO:0010957', 'GO:0010980', 'GO:0010987', 'GO:0014025', 'GO:0014038', 'GO:0014709', 'GO:0014738', 'GO:0014743', 'GO:0014810', 'GO:0014826', 'GO:0014831', 'GO:0014843', 'GO:0014857', 'GO:0014861', 'GO:0014896', 'GO:0015044', 'GO:0015052', 'GO:0015091', 'GO:0015092', 'GO:0015100', 'GO:0015113', 'GO:0015117', 'GO:0015130', 'GO:0015134', 'GO:0015147', 'GO:0015159', 'GO:0015164', 'GO:0015195', 'GO:0015209', 'GO:0015216', 'GO:0015312', 'GO:0015315', 'GO:0015327', 'GO:0015341', 'GO:0015360', 'GO:0015371', 'GO:0015374', 'GO:0015377', 'GO:0015387', 'GO:0015407', 'GO:0015411', 'GO:0015412', 'GO:0015417', 'GO:0015423', 'GO:0015430', 'GO:0015437', 'GO:0015453', 'GO:0015471', 'GO:0015473', 'GO:0015478', 'GO:0015481', 'GO:0015483', 'GO:0015487', 'GO:0015496', 'GO:0015503', 'GO:0015514', 'GO:0015516', 'GO:0015518', 'GO:0015519', 'GO:0015526', 'GO:0015527', 'GO:0015528', 'GO:0015530', 'GO:0015531', 'GO:0015535', 'GO:0015538', 'GO:0015540', 'GO:0015546', 'GO:0015556', 'GO:0015558', 'GO:0015567', 'GO:0015568', 'GO:0015592', 'GO:0015603', 'GO:0015607', 'GO:0015625', 'GO:0015638', 'GO:0015640', 'GO:0015648', 'GO:0015649', 'GO:0015654', 'GO:0015661', 'GO:0015666', 'GO:0015673', 'GO:0015676', 'GO:0015687', 'GO:0015709', 'GO:0015710', 'GO:0015712', 'GO:0015716', 'GO:0015726', 'GO:0015728', 'GO:0015733', 'GO:0015736', 'GO:0015745', 'GO:0015751', 'GO:0015752', 'GO:0015753', 'GO:0015754', 'GO:0015762', 'GO:0015764', 'GO:0015765', 'GO:0015769', 'GO:0015772', 'GO:0015796', 'GO:0015814', 'GO:0015826', 'GO:0015830', 'GO:0015834', 'GO:0015836', 'GO:0015895', 'GO:0015912', 'GO:0015942', 'GO:0015944', 'GO:0015949', 'GO:0015950', 'GO:0015951', 'GO:0015969', 'GO:0015980', 'GO:0016013', 'GO:0016068', 'GO:0016076', 'GO:0016150', 'GO:0016154', 'GO:0016158', 'GO:0016170', 'GO:0016230', 'GO:0016240', 'GO:0016250', 'GO:0016256', 'GO:0016273', 'GO:0016278', 'GO:0016289', 'GO:0016309', 'GO:0016362', 'GO:0016420', 'GO:0016430', 'GO:0016434', 'GO:0016436', 'GO:0016469', 'GO:0016488', 'GO:0016517', 'GO:0016661', 'GO:0016672', 'GO:0016675', 'GO:0016701', 'GO:0016713', 'GO:0016723', 'GO:0016726', 'GO:0016748', 'GO:0016774', 'GO:0016775', 'GO:0016778', 'GO:0016803', 'GO:0016840', 'GO:0016844', 'GO:0016855', 'GO:0016862', 'GO:0016879', 'GO:0016896', 'GO:0016901', 'GO:0016903', 'GO:0016935', 'GO:0016964', 'GO:0016979', 'GO:0016997', 'GO:0017001', 'GO:0017042', 'GO:0017105', 'GO:0017130', 'GO:0017161', 'GO:0017187', 'GO:0017192', 'GO:0018003', 'GO:0018008', 'GO:0018013', 'GO:0018030', 'GO:0018063', 'GO:0018076', 'GO:0018125', 'GO:0018153', 'GO:0018169', 'GO:0018206', 'GO:0018240', 'GO:0018277', 'GO:0018366', 'GO:0018395', 'GO:0018467', 'GO:0018549', 'GO:0018601', 'GO:0018756', 'GO:0018771', 'GO:0018773', 'GO:0018907', 'GO:0018910', 'GO:0019043', 'GO:0019057', 'GO:0019062', 'GO:0019064', 'GO:0019068', 'GO:0019074', 'GO:0019075', 'GO:0019076', 'GO:0019082', 'GO:0019083', 'GO:0019085', 'GO:0019086', 'GO:0019119', 'GO:0019146', 'GO:0019147', 'GO:0019149', 'GO:0019152', 'GO:0019159', 'GO:0019165', 'GO:0019168', 'GO:0019180', 'GO:0019185', 'GO:0019250', 'GO:0019272', 'GO:0019292', 'GO:0019294', 'GO:0019303', 'GO:0019310', 'GO:0019316', 'GO:0019319', 'GO:0019323', 'GO:0019324', 'GO:0019345', 'GO:0019353', 'GO:0019380', 'GO:0019391', 'GO:0019394', 'GO:0019404', 'GO:0019440', 'GO:0019480', 'GO:0019518', 'GO:0019529', 'GO:0019538', 'GO:0019542', 'GO:0019552', 'GO:0019569', 'GO:0019580', 'GO:0019584', 'GO:0019588', 'GO:0019592', 'GO:0019595', 'GO:0019622', 'GO:0019645', 'GO:0019660', 'GO:0019664', 'GO:0019665', 'GO:0019686', 'GO:0019747', 'GO:0019763', 'GO:0019766', 'GO:0019769', 'GO:0019771', 'GO:0019772', 'GO:0019783', 'GO:0019812', 'GO:0019854', 'GO:0019869', 'GO:0019914', 'GO:0019918', 'GO:0019959', 'GO:0019964', 'GO:0019981', 'GO:0020011', 'GO:0020014', 'GO:0020018', 'GO:0020022', 'GO:0020026', 'GO:0020033', 'GO:0020035', 'GO:0020036', 'GO:0021531', 'GO:0021538', 'GO:0021552', 'GO:0021577', 'GO:0021578', 'GO:0021654', 'GO:0021661', 'GO:0021663', 'GO:0021664', 'GO:0021667', 'GO:0021744', 'GO:0021757', 'GO:0021758', 'GO:0021812', 'GO:0021836', 'GO:0021898', 'GO:0021899', 'GO:0021972', 'GO:0021982', 'GO:0022001', 'GO:0022609', 'GO:0022613', 'GO:0022858', 'GO:0022870', 'GO:0022877', 'GO:0022883', 'GO:0023021', 'GO:0023025', 'GO:0023026', 'GO:0023029', 'GO:0030107', 'GO:0030108', 'GO:0030109', 'GO:0030152', 'GO:0030157', 'GO:0030164', 'GO:0030167', 'GO:0030184', 'GO:0030197', 'GO:0030221', 'GO:0030226', 'GO:0030233', 'GO:0030251', 'GO:0030290', 'GO:0030293', 'GO:0030298', 'GO:0030313', 'GO:0030366', 'GO:0030369', 'GO:0030379', 'GO:0030380', 'GO:0030392', 'GO:0030451', 'GO:0030526', 'GO:0030613', 'GO:0030622', 'GO:0030624', 'GO:0030629', 'GO:0030681', 'GO:0030694', 'GO:0030748', 'GO:0030750', 'GO:0030760', 'GO:0030798', 'GO:0030813', 'GO:0030884', 'GO:0030964', 'GO:0030973', 'GO:0031084', 'GO:0031085', 'GO:0031088', 'GO:0031089', 'GO:0031092', 'GO:0031093', 'GO:0031094', 'GO:0031101', 'GO:0031220', 'GO:0031240', 'GO:0031241', 'GO:0031250', 'GO:0031258', 'GO:0031281', 'GO:0031313', 'GO:0031342', 'GO:0031400', 'GO:0031401', 'GO:0031413', 'GO:0031420', 'GO:0031421', 'GO:0031504', 'GO:0031531', 'GO:0031544', 'GO:0031555', 'GO:0031556', 'GO:0031585', 'GO:0031685', 'GO:0031695', 'GO:0031696', 'GO:0031711', 'GO:0031715', 'GO:0031720', 'GO:0031728', 'GO:0031735', 'GO:0031741', 'GO:0031755', 'GO:0031764', 'GO:0031765', 'GO:0031766', 'GO:0031767', 'GO:0031780', 'GO:0031783', 'GO:0031788', 'GO:0031836', 'GO:0031838', 'GO:0031843', 'GO:0031867', 'GO:0031870', 'GO:0031891', 'GO:0031892', 'GO:0031960', 'GO:0031962', 'GO:0031992', 'GO:0031996', 'GO:0032002', 'GO:0032003', 'GO:0032029', 'GO:0032034', 'GO:0032058', 'GO:0032067', 'GO:0032071', 'GO:0032072', 'GO:0032074', 'GO:0032076', 'GO:0032077', 'GO:0032078', 'GO:0032079', 'GO:0032089', 'GO:0032090', 'GO:0032136', 'GO:0032142', 'GO:0032143', 'GO:0032144', 'GO:0032145', 'GO:0032181', 'GO:0032190', 'GO:0032201', 'GO:0032237', 'GO:0032261', 'GO:0032267', 'GO:0032273', 'GO:0032274', 'GO:0032277', 'GO:0032300', 'GO:0032305', 'GO:0032306', 'GO:0032311', 'GO:0032329', 'GO:0032347', 'GO:0032356', 'GO:0032358', 'GO:0032359', 'GO:0032375', 'GO:0032384', 'GO:0032388', 'GO:0032395', 'GO:0032396', 'GO:0032397', 'GO:0032399', 'GO:0032405', 'GO:0032406', 'GO:0032408', 'GO:0032410', 'GO:0032412', 'GO:0032414', 'GO:0032423', 'GO:0032425', 'GO:0032427', 'GO:0032458', 'GO:0032464', 'GO:0032475', 'GO:0032498', 'GO:0032506', 'GO:0032539', 'GO:0032597', 'GO:0032653', 'GO:0032673', 'GO:0032683', 'GO:0032685', 'GO:0032686', 'GO:0032712', 'GO:0032738', 'GO:0032739', 'GO:0032759', 'GO:0032761', 'GO:0032773', 'GO:0032802', 'GO:0032817', 'GO:0032834', 'GO:0032848', 'GO:0032902', 'GO:0032909', 'GO:0032912', 'GO:0032913', 'GO:0032920', 'GO:0032965', 'GO:0032976', 'GO:0032986', 'GO:0032996', 'GO:0033045', 'GO:0033051', 'GO:0033059', 'GO:0033063', 'GO:0033094', 'GO:0033135', 'GO:0033141', 'GO:0033195', 'GO:0033228', 'GO:0033232', 'GO:0033233', 'GO:0033256', 'GO:0033257', 'GO:0033276', 'GO:0033293', 'GO:0033333', 'GO:0033334', 'GO:0033336', 'GO:0033338', 'GO:0033339', 'GO:0033359', 'GO:0033396', 'GO:0033477', 'GO:0033489', 'GO:0033514', 'GO:0033521', 'GO:0033543', 'GO:0033593', 'GO:0033608', 'GO:0033609', 'GO:0033624', 'GO:0033711', 'GO:0033739', 'GO:0033748', 'GO:0033756', 'GO:0033785', 'GO:0033786', 'GO:0033787', 'GO:0033812', 'GO:0033831', 'GO:0033856', 'GO:0033861', 'GO:0033863', 'GO:0033890', 'GO:0033969', 'GO:0033982', 'GO:0034012', 'GO:0034015', 'GO:0034017', 'GO:0034023', 'GO:0034024', 'GO:0034026', 'GO:0034028', 'GO:0034078', 'GO:0034105', 'GO:0034125', 'GO:0034126', 'GO:0034156', 'GO:0034161', 'GO:0034163', 'GO:0034184', 'GO:0034186', 'GO:0034191', 'GO:0034194', 'GO:0034195', 'GO:0034200', 'GO:0034204', 'GO:0034213', 'GO:0034265', 'GO:0034289', 'GO:0034318', 'GO:0034329', 'GO:0034344', 'GO:0034345', 'GO:0034358', 'GO:0034359', 'GO:0034360', 'GO:0034366', 'GO:0034369', 'GO:0034373', 'GO:0034421', 'GO:0034436', 'GO:0034441', 'GO:0034482', 'GO:0034494', 'GO:0034545', 'GO:0034552', 'GO:0034589', 'GO:0034590', 'GO:0034591', 'GO:0034597', 'GO:0034650', 'GO:0034656', 'GO:0034665', 'GO:0034668', 'GO:0034669', 'GO:0034672', 'GO:0034673', 'GO:0034674', 'GO:0034675', 'GO:0034678', 'GO:0034680', 'GO:0034681', 'GO:0034682', 'GO:0034687', 'GO:0034689', 'GO:0034700', 'GO:0034714', 'GO:0034715', 'GO:0034719', 'GO:0034776', 'GO:0034875', 'GO:0034959', 'GO:0035118', 'GO:0035122', 'GO:0035124', 'GO:0035138', 'GO:0035141', 'GO:0035142', 'GO:0035143', 'GO:0035246', 'GO:0035281', 'GO:0035303', 'GO:0035348', 'GO:0035349', 'GO:0035350', 'GO:0035354', 'GO:0035378', 'GO:0035382', 'GO:0035395', 'GO:0035401', 'GO:0035403', 'GO:0035433', 'GO:0035443', 'GO:0035460', 'GO:0035461', 'GO:0035462', 'GO:0035469', 'GO:0035474', 'GO:0035475', 'GO:0035477', 'GO:0035479', 'GO:0035491', 'GO:0035500', 'GO:0035501', 'GO:0035513', 'GO:0035523', 'GO:0035526', 'GO:0035527', 'GO:0035562', 'GO:0035572', 'GO:0035573', 'GO:0035577', 'GO:0035578', 'GO:0035579', 'GO:0035580', 'GO:0035581', 'GO:0035594', 'GO:0035599', 'GO:0035643', 'GO:0035651', 'GO:0035665', 'GO:0035672', 'GO:0035675', 'GO:0035676', 'GO:0035677', 'GO:0035683', 'GO:0035689', 'GO:0035695', 'GO:0035722', 'GO:0035723', 'GO:0035730', 'GO:0035747', 'GO:0035757', 'GO:0035758', 'GO:0035759', 'GO:0035768', 'GO:0035775', 'GO:0035778', 'GO:0035779', 'GO:0035785', 'GO:0035844', 'GO:0035853', 'GO:0035854', 'GO:0035867', 'GO:0035868', 'GO:0035871', 'GO:0035872', 'GO:0035888', 'GO:0035889', 'GO:0035927', 'GO:0035928', 'GO:0035936', 'GO:0035941', 'GO:0035945', 'GO:0035946', 'GO:0035964', 'GO:0035985', 'GO:0036021', 'GO:0036024', 'GO:0036025', 'GO:0036026', 'GO:0036027', 'GO:0036028', 'GO:0036029', 'GO:0036030', 'GO:0036105', 'GO:0036111', 'GO:0036112', 'GO:0036113', 'GO:0036115', 'GO:0036117', 'GO:0036125', 'GO:0036131', 'GO:0036134', 'GO:0036139', 'GO:0036140', 'GO:0036148', 'GO:0036153', 'GO:0036155', 'GO:0036173', 'GO:0036185', 'GO:0036198', 'GO:0036213', 'GO:0036243', 'GO:0036250', 'GO:0036260', 'GO:0036265', 'GO:0036307', 'GO:0036308', 'GO:0036316', 'GO:0036317', 'GO:0036323', 'GO:0036332', 'GO:0036337', 'GO:0036355', 'GO:0036397', 'GO:0036411', 'GO:0036412', 'GO:0036448', 'GO:0036458', 'GO:0036461', 'GO:0036462', 'GO:0036463', 'GO:0036470', 'GO:0036478', 'GO:0036479', 'GO:0036480', 'GO:0036502', 'GO:0036505', 'GO:0036506', 'GO:0036524', 'GO:0038009', 'GO:0038018', 'GO:0038033', 'GO:0038035', 'GO:0038041', 'GO:0038048', 'GO:0038091', 'GO:0038093', 'GO:0038102', 'GO:0038110', 'GO:0038111', 'GO:0038112', 'GO:0038113', 'GO:0038117', 'GO:0038120', 'GO:0038121', 'GO:0038124', 'GO:0038127', 'GO:0038128', 'GO:0038129', 'GO:0038143', 'GO:0038146', 'GO:0038147', 'GO:0038154', 'GO:0038155', 'GO:0038157', 'GO:0038159', 'GO:0038161', 'GO:0038164', 'GO:0038165', 'GO:0038182', 'GO:0038184', 'GO:0038195', 'GO:0038196', 'GO:0039008', 'GO:0039010', 'GO:0039015', 'GO:0039021', 'GO:0039023', 'GO:0039530', 'GO:0039532', 'GO:0039534', 'GO:0039535', 'GO:0039537', 'GO:0039552', 'GO:0039585', 'GO:0039654', 'GO:0039692', 'GO:0039695', 'GO:0039702', 'GO:0040033', 'GO:0042007', 'GO:0042010', 'GO:0042011', 'GO:0042012', 'GO:0042017', 'GO:0042019', 'GO:0042020', 'GO:0042022', 'GO:0042068', 'GO:0042174', 'GO:0042197', 'GO:0042269', 'GO:0042279', 'GO:0042286', 'GO:0042287', 'GO:0042313', 'GO:0042322', 'GO:0042333', 'GO:0042339', 'GO:0042355', 'GO:0042356', 'GO:0042361', 'GO:0042377', 'GO:0042402', 'GO:0042454', 'GO:0042495', 'GO:0042496', 'GO:0042509', 'GO:0042532', 'GO:0042540', 'GO:0042565', 'GO:0042578', 'GO:0042601', 'GO:0042612', 'GO:0042619', 'GO:0042636', 'GO:0042658', 'GO:0042663', 'GO:0042665', 'GO:0042666', 'GO:0042671', 'GO:0042704', 'GO:0042772', 'GO:0042777', 'GO:0042827', 'GO:0042836', 'GO:0042838', 'GO:0042846', 'GO:0042851', 'GO:0042853', 'GO:0042873', 'GO:0042875', 'GO:0042881', 'GO:0042884', 'GO:0042885', 'GO:0042893', 'GO:0042897', 'GO:0042912', 'GO:0042914', 'GO:0042918', 'GO:0042920', 'GO:0042924', 'GO:0042928', 'GO:0042944', 'GO:0042945', 'GO:0042947', 'GO:0042959', 'GO:0042960', 'GO:0042968', 'GO:0042970', 'GO:0042984', 'GO:0042988', 'GO:0043012', 'GO:0043039', 'GO:0043062', 'GO:0043076', 'GO:0043093', 'GO:0043097', 'GO:0043099', 'GO:0043102', 'GO:0043163', 'GO:0043164', 'GO:0043170', 'GO:0043181', 'GO:0043213', 'GO:0043221', 'GO:0043225', 'GO:0043257', 'GO:0043260', 'GO:0043282', 'GO:0043299', 'GO:0043311', 'GO:0043318', 'GO:0043323', 'GO:0043365', 'GO:0043414', 'GO:0043420', 'GO:0043442', 'GO:0043468', 'GO:0043485', 'GO:0043509', 'GO:0043532', 'GO:0043571', 'GO:0043580', 'GO:0043593', 'GO:0043595', 'GO:0043597', 'GO:0043600', 'GO:0043649', 'GO:0043667', 'GO:0043726', 'GO:0043737', 'GO:0043739', 'GO:0043751', 'GO:0043759', 'GO:0043768', 'GO:0043795', 'GO:0043798', 'GO:0043811', 'GO:0043821', 'GO:0043822', 'GO:0043825', 'GO:0043828', 'GO:0043838', 'GO:0043846', 'GO:0043849', 'GO:0043862', 'GO:0043872', 'GO:0043873', 'GO:0043874', 'GO:0043875', 'GO:0043883', 'GO:0043887', 'GO:0043891', 'GO:0043894', 'GO:0043906', 'GO:0043907', 'GO:0043918', 'GO:0043921', 'GO:0043939', 'GO:0043950', 'GO:0043951', 'GO:0043957', 'GO:0043999', 'GO:0044013', 'GO:0044024', 'G

In [10]:
print("--- Codification results ---")
print(f"Label shape (Y_train): {Y_train_sparse.shape}")
print(f"Object type: {type(Y_train_sparse)}") 
# <class 'scipy.sparse.csr.csr_matrix'>
print(f"RAM used (aprox): {Y_train_sparse.data.nbytes / 1024**2:.2f} MB")

--- Codification results ---
Label shape (Y_train): (58361, 22828)
Object type: <class 'scipy.sparse._csr.csr_matrix'>
RAM used (aprox): 2.70 MB

In [11]:
# Save Y_train_sparse and Y_val_sparse
np.save(y_train_sparse_path, Y_train_sparse)
np.save(y_val_sparse_path, Y_val_sparse)

# Save classes.npy (used later)

In [12]:
from tqdm import tqdm

In [13]:
# We use a SET to automatically store only unique terms
unique_classes = set()

# Iterate row by row to save RAM
for row in tqdm(df_train['go_terms']):
    terms = safe_eval_and_flatten(row)
    unique_classes.update(terms)

100%|██████████| 58361/58361 [00:01<00:00, 45539.96it/s]

In [14]:
sorted_classes = sorted(list(unique_classes))
classes_array = np.array(sorted_classes)

print(f"Number of unique GO terms in training set: {len(sorted_classes)}")

Number of unique GO terms in training set: 22828

In [15]:
num_cols_matrix = Y_train_sparse.shape[1]
    
if len(classes_array) == num_cols_matrix:
    print("OK! The number of classes matches the trained matrix.")
    
    # Save so we don't need to repeat this ever again
    np.save(classes_path, classes_array)
    print(f"File saved to: {output_path}classes.npy")
else:
    print(f"WARNING: Size mismatch.")
    print(f"Unique terms found in CSV: {len(classes_array)}")
    print(f"Columns in sparse matrix: {num_cols_matrix}")
    print("Check if data filtering was identical.")

OK! The number of classes matches the trained matrix.
File saved to: ../input/classes.npy

# Save IA_weights (used on validation)

In [16]:
df_weights = pd.read_csv(ia_weights_path, sep="\t", names=["go_terms", "ia"])
df_weights.head()

     go_terms        ia
0  GO:0000001  0.000000
1  GO:0000002  2.849666
2  GO:0000011  0.137504
3  GO:0000012  6.038630
4  GO:0000017  0.514573

In [17]:
ia_score_map = df_weights.set_index('go_terms')['ia'].to_dict()

In [18]:
MIN_IA_SCORE = 0.0

In [19]:
LABEL_COUNT = len(mlb.classes_)
LABEL_COUNT

22828

In [20]:
ia_weights_ordered = np.zeros(LABEL_COUNT, dtype=np.float32)

In [21]:
for i, go_term in enumerate(mlb.classes_):
    weight = ia_score_map.get(go_term, MIN_IA_SCORE)
    ia_weights_ordered[i] = weight

In [22]:
ia_weights_ordered.shape

(22828,)

In [23]:
np.save(final_ia_weights_path, ia_weights_ordered)