In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
import ast
from scipy.sparse import csr_matrix

In [2]:
output_path = "../input/"
train_path = output_path + "train/"
val_path = output_path + "val/"

train_df = train_path + "train_fold0_split.csv"
val_df = val_path + "val_fold0_split.csv"
train_emb = train_path + "train_fold0_embeddings.npy"
val_emb = val_path + "val_fold0_embeddings.npy"

y_train_sparse_path = train_path + "Y_train_fold0_sparse.npy"
y_val_sparse_path = val_path + "Y_val_fold0_sparse.npy"

classes_path = output_path + "classes_fold0.npy"
ia_weights_path = "../../general_input/IA.tsv"
final_ia_weights_path = output_path + "ia_weights_fold0.npy"

In [3]:
df_train = pd.read_csv(train_df)
df_val = pd.read_csv(val_df)
X_train = np.load(train_emb)
X_val = np.load(val_emb)

In [4]:
def safe_eval_and_flatten(x):
    if pd.notna(x) and x.strip().startswith('['):
        try:
            # 1. Convert string to list of lists (e.g., "[['GO:1'], ['GO:2', 'GO:3']]")
            evaluated_list_of_lists = ast.literal_eval(x)
            
            # 2. Flatten the list of lists into a single list
            return [term for sublist in evaluated_list_of_lists for term in sublist]
        except:
            # Return empty list if evaluation fails
            return []
    return []

def parse_go_terms_flattened(go_terms_series):
    # Apply the safe evaluation and flattening function to the series
    return go_terms_series.apply(safe_eval_and_flatten)

In [5]:
df_train

,db,id,name,full_name,organism,taxon_x,gen,PE,SV,sequence_x,length,go_terms,aspect,sequence_y,seq_length,taxon_y,rep_id,fold
0,sp,A0A023FBW4,E1142_AMBCJ,Evasin P1142,Amblyomma cajennense,34607,NaN,3,1,MTSHGAVKIAIFAVIALHSIFECLSKPQILQRTDHSTDSDWDPQMC...,97,[['GO:0019958']],['F'],MTSHGAVKIAIFAVIALHSIFECLSKPQILQRTDHSTDSDWDPQMC...,97,34607,A0A023FBW4,4
1,sp,A0A023FBW7,EV546_AMBCJ,Evasin P546,Amblyomma cajennense,34607,NaN,3,1,MKVLLYIAASCLMLLALNVSAENTQQEEEDYDYGTDTCPFPVLANK...,118,[['GO:0019957']],['F'],MKVLLYIAASCLMLLALNVSAENTQQEEEDYDYGTDTCPFPVLANK...,118,34607,A0A023FBW7,1
2,sp,A0A023FDY8,EV974_AMBCJ,Evasin P974,Amblyomma cajennense,34607,NaN,1,1,MKVLLCIAASCLMLLALNVSAENTQQEEQDYDYGTDTCPFPVLANK...,118,[['GO:0019957']],['F'],MKVLLCIAASCLMLLALNVSAENTQQEEQDYDYGTDTCPFPVLANK...,118,34607,A0A023FBW7,1
3,sp,A0A023FF81,E1126_AMBCJ,Evasin P1126,Amblyomma cajennense,34607,NaN,3,1,MTSHSAVRIAIFAVIALHSIFECLSKPQILQRTDKSTDSEWDPQTC...,90,[['GO:0019958']],['F'],MTSHSAVRIAIFAVIALHSIFECLSKPQILQRTDKSTDSEWDPQTC...,90,34607,A0A023FBW4,4
4,sp,A0A023FFB5,EV983_AMBCJ,Evasin P983,Amblyomma cajennense,34607,NaN,3,2,MKASFCVIASCLVVFALKGTAEDTGTEDDFDYGNTGCPFPVLGNYK...,119,[['GO:0019957']],['F'],MKASFCVIASCLVVFALKGTAEDTGTEDDFDYGNTGCPFPVLGNYK...,119,34607,L7M8Z8,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65749,sp,X2JDY8,RHGF_DROME,Rho GTPase-activating protein Graf,Drosophila melanogaster,7227,Graf,1,1,MGGGKNVRRGLEPLEFEECIVDSPDFRENLNRHEKELDHTSHQIKR...,1025,"[['GO:0140036'], ['GO:0031410'], ['GO:0002092'...","['F', 'C', 'P', 'P', 'C', 'C', 'C', 'F', 'P', ...",MGGGKNVRRGLEPLEFEECIVDSPDFRENLNRHEKELDHTSHQIKR...,1025,7227,X2JDY8,3
65750,sp,X4Y2L4,LHYAL_HIRNI,Hyaluronoglucuronidase,Hirudo nipponia,42736,NaN,1,1,MKEIAVTIDDKNVIASVSESFHGVAFDASLFSPKGLWSFVDITSPK...,489,"[['GO:0033906'], ['GO:0030214']]","['F', 'P']",MKEIAVTIDDKNVIASVSESFHGVAFDASLFSPKGLWSFVDITSPK...,489,42736,Q9FF10,2
65751,sp,X5JA13,SECAA_ARATH,Exocyst complex component SEC10a,Arabidopsis thaliana,3702,SEC10a,1,1,MTEGIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,825,"[['GO:0070062'], ['GO:0005829'], ['GO:0005515'...","['C', 'C', 'F', 'C', 'C', 'C', 'C', 'P']",MTEGIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,825,3702,X5JB51,1
65752,sp,X5JB51,SECAB_ARATH,Exocyst complex component SEC10b,Arabidopsis thaliana,3702,SEC10b,1,1,MTERIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,829,"[['GO:0070062'], ['GO:0005829'], ['GO:0005886'...","['C', 'C', 'C', 'C', 'C', 'C', 'P', 'F']",MTERIRARGPRSSSVNSVPLILDIEDFKGDFSFDALFGNLVNDLLP...,829,3702,X5JB51,1
65753,sp,X5M5N0,WNK_CAEEL,Serine/threonine-protein kinase WNK,Caenorhabditis elegans,6239,wnk-1,1,1,MPDSITNGGRPPAPPSSVSSTTASTTGNFGTRRRLVNRIKKVDELH...,1850,"[['GO:0140693'], ['GO:0140694'], ['GO:0006884'...","['F', 'P', 'P', 'P', 'F', 'P', 'P', 'P']",MPDSITNGGRPPAPPSSVSSTTASTTGNFGTRRRLVNRIKKVDELH...,1850,6239,X5M5N0,2

In [6]:
y_train_lists = parse_go_terms_flattened(df_train['go_terms'])
y_val_lists = parse_go_terms_flattened(df_val['go_terms'])

In [7]:
# Binarizer
mlb = MultiLabelBinarizer(sparse_output=True)

In [8]:
# Codification adjustment
Y_train_sparse = mlb.fit_transform(y_train_lists)

In [9]:
Y_val_sparse = mlb.transform(y_val_lists)

/home/maria/miniconda3/envs/torch_env_kaggle_wi/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['GO:0000041', 'GO:0000252', 'GO:0000374', 'GO:0000401', 'GO:0001095', 'GO:0001172', 'GO:0001173', 'GO:0001512', 'GO:0001576', 'GO:0001607', 'GO:0001631', 'GO:0001632', 'GO:0001677', 'GO:0001695', 'GO:0001705', 'GO:0001770', 'GO:0001790', 'GO:0001792', 'GO:0001806', 'GO:0001807', 'GO:0001808', 'GO:0001815', 'GO:0001830', 'GO:0001868', 'GO:0001910', 'GO:0001980', 'GO:0001985', 'GO:0001990', 'GO:0001993', 'GO:0002014', 'GO:0002041', 'GO:0002112', 'GO:0002132', 'GO:0002152', 'GO:0002172', 'GO:0002178', 'GO:0002194', 'GO:0002206', 'GO:0002268', 'GO:0002364', 'GO:0002412', 'GO:0002414', 'GO:0002420', 'GO:0002443', 'GO:0002451', 'GO:0002460', 'GO:0002462', 'GO:0002476', 'GO:0002477', 'GO:0002538', 'GO:0002561', 'GO:0002579', 'GO:0002617', 'GO:0002643', 'GO:0002676', 'GO:0002699', 'GO:0002715', 'GO:0002828', 'GO:0002834', 'GO:0002840', 'GO:0002878', 'GO:0002901', 'GO:0002927', 'GO:0002932', 'GO:0003026', 'GO:0003057', 'GO:0003095', 'GO:0003172', 'GO:0003175', 'GO:0003185', 'GO:0003261', 'GO:0003305', 'GO:0003308', 'GO:0003313', 'GO:0003314', 'GO:0003317', 'GO:0003327', 'GO:0003832', 'GO:0003838', 'GO:0003864', 'GO:0003870', 'GO:0003871', 'GO:0003878', 'GO:0004013', 'GO:0004028', 'GO:0004030', 'GO:0004039', 'GO:0004052', 'GO:0004054', 'GO:0004070', 'GO:0004084', 'GO:0004087', 'GO:0004088', 'GO:0004119', 'GO:0004149', 'GO:0004153', 'GO:0004341', 'GO:0004350', 'GO:0004361', 'GO:0004372', 'GO:0004401', 'GO:0004419', 'GO:0004423', 'GO:0004424', 'GO:0004456', 'GO:0004458', 'GO:0004489', 'GO:0004498', 'GO:0004500', 'GO:0004501', 'GO:0004502', 'GO:0004507', 'GO:0004509', 'GO:0004517', 'GO:0004569', 'GO:0004576', 'GO:0004610', 'GO:0004611', 'GO:0004613', 'GO:0004618', 'GO:0004698', 'GO:0004773', 'GO:0004777', 'GO:0004825', 'GO:0004836', 'GO:0004847', 'GO:0004848', 'GO:0004876', 'GO:0004878', 'GO:0004932', 'GO:0004974', 'GO:0004982', 'GO:0005003', 'GO:0005004', 'GO:0005017', 'GO:0005018', 'GO:0005043', 'GO:0005046', 'GO:0005175', 'GO:0005219', 'GO:0005458', 'GO:0005499', 'GO:0005584', 'GO:0005586', 'GO:0005631', 'GO:0005821', 'GO:0005945', 'GO:0005951', 'GO:0006061', 'GO:0006090', 'GO:0006146', 'GO:0006316', 'GO:0006431', 'GO:0006501', 'GO:0006522', 'GO:0006549', 'GO:0006603', 'GO:0006648', 'GO:0006668', 'GO:0006705', 'GO:0006709', 'GO:0006715', 'GO:0006723', 'GO:0006792', 'GO:0006973', 'GO:0007014', 'GO:0007308', 'GO:0007371', 'GO:0007425', 'GO:0007462', 'GO:0007490', 'GO:0007555', 'GO:0008012', 'GO:0008124', 'GO:0008169', 'GO:0008261', 'GO:0008294', 'GO:0008309', 'GO:0008316', 'GO:0008346', 'GO:0008403', 'GO:0008443', 'GO:0008470', 'GO:0008493', 'GO:0008507', 'GO:0008523', 'GO:0008551', 'GO:0008609', 'GO:0008626', 'GO:0008664', 'GO:0008676', 'GO:0008684', 'GO:0008697', 'GO:0008701', 'GO:0008705', 'GO:0008715', 'GO:0008733', 'GO:0008736', 'GO:0008755', 'GO:0008760', 'GO:0008767', 'GO:0008779', 'GO:0008790', 'GO:0008834', 'GO:0008836', 'GO:0008866', 'GO:0008888', 'GO:0008892', 'GO:0008903', 'GO:0008926', 'GO:0008938', 'GO:0008939', 'GO:0008957', 'GO:0008960', 'GO:0008964', 'GO:0008965', 'GO:0008980', 'GO:0008983', 'GO:0009025', 'GO:0009026', 'GO:0009027', 'GO:0009028', 'GO:0009030', 'GO:0009040', 'GO:0009045', 'GO:0009069', 'GO:0009151', 'GO:0009200', 'GO:0009212', 'GO:0009216', 'GO:0009223', 'GO:0009233', 'GO:0009260', 'GO:0009341', 'GO:0009431', 'GO:0009496', 'GO:0009516', 'GO:0009594', 'GO:0009606', 'GO:0009701', 'GO:0009708', 'GO:0009709', 'GO:0009760', 'GO:0009784', 'GO:0009895', 'GO:0009899', 'GO:0009921', 'GO:0010024', 'GO:0010062', 'GO:0010095', 'GO:0010101', 'GO:0010127', 'GO:0010138', 'GO:0010184', 'GO:0010185', 'GO:0010298', 'GO:0010299', 'GO:0010327', 'GO:0010348', 'GO:0010349', 'GO:0010352', 'GO:0010355', 'GO:0010356', 'GO:0010357', 'GO:0010398', 'GO:0010401', 'GO:0010407', 'GO:0010413', 'GO:0010478', 'GO:0010558', 'GO:0010610', 'GO:0010663', 'GO:0010736', 'GO:0010858', 'GO:0010879', 'GO:0010920', 'GO:0010947', 'GO:0010981', 'GO:0014008', 'GO:0014038', 'GO:0014703', 'GO:0014734', 'GO:0014739', 'GO:0014740', 'GO:0014743', 'GO:0014804', 'GO:0014813', 'GO:0014843', 'GO:0014861', 'GO:0014881', 'GO:0014906', 'GO:0015016', 'GO:0015024', 'GO:0015094', 'GO:0015100', 'GO:0015148', 'GO:0015315', 'GO:0015317', 'GO:0015327', 'GO:0015415', 'GO:0015419', 'GO:0015434', 'GO:0015473', 'GO:0015481', 'GO:0015498', 'GO:0015516', 'GO:0015526', 'GO:0015527', 'GO:0015530', 'GO:0015540', 'GO:0015552', 'GO:0015558', 'GO:0015575', 'GO:0015576', 'GO:0015655', 'GO:0015676', 'GO:0015712', 'GO:0015730', 'GO:0015733', 'GO:0015745', 'GO:0015762', 'GO:0015773', 'GO:0015814', 'GO:0015830', 'GO:0015880', 'GO:0015950', 'GO:0015970', 'GO:0015988', 'GO:0016043', 'GO:0016106', 'GO:0016155', 'GO:0016156', 'GO:0016205', 'GO:0016215', 'GO:0016340', 'GO:0016488', 'GO:0016497', 'GO:0016501', 'GO:0016521', 'GO:0016543', 'GO:0016545', 'GO:0016546', 'GO:0016620', 'GO:0016639', 'GO:0016652', 'GO:0016675', 'GO:0016677', 'GO:0016715', 'GO:0016719', 'GO:0016723', 'GO:0016726', 'GO:0016742', 'GO:0016778', 'GO:0016838', 'GO:0016875', 'GO:0016889', 'GO:0016895', 'GO:0016990', 'GO:0016995', 'GO:0017083', 'GO:0017090', 'GO:0017105', 'GO:0017168', 'GO:0017186', 'GO:0018009', 'GO:0018025', 'GO:0018119', 'GO:0018153', 'GO:0018272', 'GO:0018484', 'GO:0018505', 'GO:0018601', 'GO:0018631', 'GO:0018659', 'GO:0018664', 'GO:0018675', 'GO:0018685', 'GO:0018756', 'GO:0018786', 'GO:0018867', 'GO:0018885', 'GO:0018901', 'GO:0018910', 'GO:0018969', 'GO:0018970', 'GO:0018985', 'GO:0019058', 'GO:0019085', 'GO:0019147', 'GO:0019159', 'GO:0019170', 'GO:0019180', 'GO:0019264', 'GO:0019280', 'GO:0019374', 'GO:0019376', 'GO:0019510', 'GO:0019542', 'GO:0019564', 'GO:0019592', 'GO:0019593', 'GO:0019643', 'GO:0019665', 'GO:0019756', 'GO:0019780', 'GO:0019782', 'GO:0019786', 'GO:0021629', 'GO:0021644', 'GO:0021659', 'GO:0021660', 'GO:0021665', 'GO:0021666', 'GO:0021742', 'GO:0021743', 'GO:0021757', 'GO:0021758', 'GO:0021768', 'GO:0021771', 'GO:0021793', 'GO:0021822', 'GO:0021924', 'GO:0021935', 'GO:0021937', 'GO:0021963', 'GO:0021989', 'GO:0021993', 'GO:0022001', 'GO:0022006', 'GO:0022013', 'GO:0022603', 'GO:0022608', 'GO:0022839', 'GO:0022877', 'GO:0030108', 'GO:0030171', 'GO:0030233', 'GO:0030273', 'GO:0030338', 'GO:0030342', 'GO:0030392', 'GO:0030409', 'GO:0030412', 'GO:0030586', 'GO:0030604', 'GO:0030640', 'GO:0030649', 'GO:0030655', 'GO:0030656', 'GO:0030662', 'GO:0030735', 'GO:0030738', 'GO:0030746', 'GO:0030751', 'GO:0030755', 'GO:0030757', 'GO:0030761', 'GO:0030766', 'GO:0030842', 'GO:0030885', 'GO:0030912', 'GO:0031002', 'GO:0031025', 'GO:0031142', 'GO:0031173', 'GO:0031240', 'GO:0031259', 'GO:0031413', 'GO:0031420', 'GO:0031504', 'GO:0031646', 'GO:0031651', 'GO:0031691', 'GO:0031700', 'GO:0031769', 'GO:0031777', 'GO:0031826', 'GO:0031835', 'GO:0031858', 'GO:0031870', 'GO:0031887', 'GO:0031921', 'GO:0031925', 'GO:0031927', 'GO:0031928', 'GO:0031947', 'GO:0031964', 'GO:0032003', 'GO:0032018', 'GO:0032029', 'GO:0032072', 'GO:0032165', 'GO:0032173', 'GO:0032181', 'GO:0032215', 'GO:0032216', 'GO:0032304', 'GO:0032305', 'GO:0032398', 'GO:0032409', 'GO:0032412', 'GO:0032653', 'GO:0032667', 'GO:0032673', 'GO:0032683', 'GO:0032759', 'GO:0032761', 'GO:0032788', 'GO:0032789', 'GO:0032799', 'GO:0032802', 'GO:0032866', 'GO:0032879', 'GO:0032896', 'GO:0032902', 'GO:0032948', 'GO:0032975', 'GO:0032996', 'GO:0033027', 'GO:0033029', 'GO:0033038', 'GO:0033094', 'GO:0033095', 'GO:0033193', 'GO:0033233', 'GO:0033257', 'GO:0033301', 'GO:0033331', 'GO:0033332', 'GO:0033371', 'GO:0033373', 'GO:0033382', 'GO:0033505', 'GO:0033511', 'GO:0033521', 'GO:0033593', 'GO:0033661', 'GO:0033707', 'GO:0033799', 'GO:0033800', 'GO:0033802', 'GO:0033803', 'GO:0033809', 'GO:0033818', 'GO:0033831', 'GO:0033842', 'GO:0033845', 'GO:0033849', 'GO:0033889', 'GO:0033942', 'GO:0033969', 'GO:0033982', 'GO:0034002', 'GO:0034005', 'GO:0034006', 'GO:0034007', 'GO:0034008', 'GO:0034009', 'GO:0034042', 'GO:0034043', 'GO:0034064', 'GO:0034069', 'GO:0034093', 'GO:0034163', 'GO:0034178', 'GO:0034183', 'GO:0034196', 'GO:0034240', 'GO:0034251', 'GO:0034280', 'GO:0034281', 'GO:0034343', 'GO:0034345', 'GO:0034373', 'GO:0034397', 'GO:0034423', 'GO:0034441', 'GO:0034479', 'GO:0034496', 'GO:0034730', 'GO:0034758', 'GO:0034761', 'GO:0034768', 'GO:0035047', 'GO:0035062', 'GO:0035124', 'GO:0035180', 'GO:0035226', 'GO:0035231', 'GO:0035292', 'GO:0035297', 'GO:0035350', 'GO:0035395', 'GO:0035403', 'GO:0035443', 'GO:0035447', 'GO:0035474', 'GO:0035478', 'GO:0035498', 'GO:0035525', 'GO:0035614', 'GO:0035643', 'GO:0035688', 'GO:0035689', 'GO:0035709', 'GO:0035712', 'GO:0035714', 'GO:0035759', 'GO:0035787', 'GO:0035789', 'GO:0035790', 'GO:0035793', 'GO:0035822', 'GO:0035849', 'GO:0035905', 'GO:0036085', 'GO:0036101', 'GO:0036105', 'GO:0036131', 'GO:0036196', 'GO:0036201', 'GO:0036202', 'GO:0036216', 'GO:0036243', 'GO:0036250', 'GO:0036265', 'GO:0036296', 'GO:0036299', 'GO:0036308', 'GO:0036317', 'GO:0036323', 'GO:0036325', 'GO:0036332', 'GO:0036403', 'GO:0036450', 'GO:0036458', 'GO:0036505', 'GO:0038032', 'GO:0038045', 'GO:0038062', 'GO:0038123', 'GO:0038129', 'GO:0038171', 'GO:0038178', 'GO:0038182', 'GO:0038184', 'GO:0039537', 'GO:0039654', 'GO:0039695', 'GO:0040021', 'GO:0042038', 'GO:0042062', 'GO:0042068', 'GO:0042181', 'GO:0042189', 'GO:0042197', 'GO:0042206', 'GO:0042263', 'GO:0042286', 'GO:0042339', 'GO:0042361', 'GO:0042366', 'GO:0042371', 'GO:0042374', 'GO:0042377', 'GO:0042435', 'GO:0042494', 'GO:0042619', 'GO:0042669', 'GO:0042704', 'GO:0042706', 'GO:0042767', 'GO:0042768', 'GO:0042821', 'GO:0042905', 'GO:0042914', 'GO:0042920', 'GO:0042924', 'GO:0042947', 'GO:0042988', 'GO:0043038', 'GO:0043039', 'GO:0043121', 'GO:0043170', 'GO:0043181', 'GO:0043221', 'GO:0043373', 'GO:0043381', 'GO:0043383', 'GO:0043468', 'GO:0043578', 'GO:0043593', 'GO:0043612', 'GO:0043639', 'GO:0043751', 'GO:0043755', 'GO:0043774', 'GO:0043795', 'GO:0043799', 'GO:0043838', 'GO:0043849', 'GO:0043858', 'GO:0043862', 'GO:0043872', 'GO:0043904', 'GO:0043957', 'GO:0043999', 'GO:0044211', 'GO:0044281', 'GO:0044302', 'GO:0044378', 'GO:0044492', 'GO:0044499', 'GO:0044524', 'GO:0044540', 'GO:0044559', 'GO:0044750', 'GO:0044781', 'GO:0044841', 'GO:0044858', 'GO:0044873', 'GO:0045015', 'GO:0045031', 'GO:0045113', 'GO:0045130', 'GO:0045230', 'GO:0045290', 'GO:0045496', 'GO:0045497', 'GO:0045517', 'GO:0045518', 'GO:0045550', 'GO:0045569', 'GO:0045610', 'GO:0045761', 'GO:0045771', 'GO:0045852', 'GO:0045855', 'GO:0045856', 'GO:0045912', 'GO:0045913', 'GO:0045928', 'GO:0045984', 'GO:0046029', 'GO:0046072', 'GO:0046098', 'GO:0046111', 'GO:0046130', 'GO:0046133', 'GO:0046173', 'GO:0046184', 'GO:0046185', 'GO:0046196', 'GO:0046247', 'GO:0046248', 'GO:0046250', 'GO:0046327', 'GO:0046333', 'GO:0046335', 'GO:0046342', 'GO:0046359', 'GO:0046364', 'GO:0046381', 'GO:0046428', 'GO:0046458', 'GO:0046461', 'GO:0046509', 'GO:0046520', 'GO:0046522', 'GO:0046539', 'GO:0046553', 'GO:0046564', 'GO:0046583', 'GO:0046608', 'GO:0046635', 'GO:0046701', 'GO:0046715', 'GO:0046720', 'GO:0046722', 'GO:0046817', 'GO:0046830', 'GO:0046936', 'GO:0047004', 'GO:0047011', 'GO:0047016', 'GO:0047018', 'GO:0047019', 'GO:0047020', 'GO:0047036', 'GO:0047046', 'GO:0047084', 'GO:0047087', 'GO:0047091', 'GO:0047094', 'GO:0047106', 'GO:0047115', 'GO:0047145', 'GO:0047172', 'GO:0047186', 'GO:0047203', 'GO:0047205', 'GO:0047259', 'GO:0047290', 'GO:0047330', 'GO:0047364', 'GO:0047407', 'GO:0047453', 'GO:0047461', 'GO:0047513', 'GO:0047545', 'GO:0047568', 'GO:0047600', 'GO:0047620', 'GO:0047652', 'GO:0047677', 'GO:0047718', 'GO:0047726', 'GO:0047743', 'GO:0047748', 'GO:0047763', 'GO:0047770', 'GO:0047783', 'GO:0047787', 'GO:0047900', 'GO:0047920', 'GO:0047921', 'GO:0047926', 'GO:0047939', 'GO:0047941', 'GO:0047953', 'GO:0047954', 'GO:0047963', 'GO:0047977', 'GO:0048034', 'GO:0048073', 'GO:0048074', 'GO:0048160', 'GO:0048212', 'GO:0048342', 'GO:0048353', 'GO:0048370', 'GO:0048459', 'GO:0048482', 'GO:0048618', 'GO:0048656', 'GO:0048698', 'GO:0048756', 'GO:0048785', 'GO:0048795', 'GO:0048797', 'GO:0048834', 'GO:0050051', 'GO:0050061', 'GO:0050086', 'GO:0050119', 'GO:0050121', 'GO:0050165', 'GO:0050199', 'GO:0050236', 'GO:0050241', 'GO:0050269', 'GO:0050297', 'GO:0050415', 'GO:0050418', 'GO:0050428', 'GO:0050429', 'GO:0050433', 'GO:0050437', 'GO:0050473', 'GO:0050479', 'GO:0050486', 'GO:0050512', 'GO:0050520', 'GO:0050547', 'GO:0050550', 'GO:0050551', 'GO:0050552', 'GO:0050554', 'GO:0050560', 'GO:0050561', 'GO:0050593', 'GO:0050596', 'GO:0050637', 'GO:0050646', 'GO:0050647', 'GO:0050648', 'GO:0050694', 'GO:0050831', 'GO:0050865', 'GO:0050923', 'GO:0050925', 'GO:0050993', 'GO:0051005', 'GO:0051008', 'GO:0051033', 'GO:0051067', 'GO:0051073', 'GO:0051128', 'GO:0051139', 'GO:0051268', 'GO:0051269', 'GO:0051413', 'GO:0051415', 'GO:0051475', 'GO:0051476', 'GO:0051479', 'GO:0051513', 'GO:0051554', 'GO:0051644', 'GO:0051730', 'GO:0051743', 'GO:0051748', 'GO:0051761', 'GO:0051765', 'GO:0051766', 'GO:0051794', 'GO:0051799', 'GO:0051875', 'GO:0051904', 'GO:0051985', 'GO:0051990', 'GO:0051998', 'GO:0052040', 'GO:0052373', 'GO:0052541', 'GO:0052577', 'GO:0052582', 'GO:0052615', 'GO:0052620', 'GO:0052631', 'GO:0052655', 'GO:0052656', 'GO:0052664', 'GO:0052678', 'GO:0052694', 'GO:0052706', 'GO:0052722', 'GO:0052737', 'GO:0052767', 'GO:0052778', 'GO:0052781', 'GO:0052814', 'GO:0052817', 'GO:0052861', 'GO:0052871', 'GO:0052873', 'GO:0052889', 'GO:0052907', 'GO:0052908', 'GO:0052909', 'GO:0052916', 'GO:0052918', 'GO:0052926', 'GO:0055006', 'GO:0055104', 'GO:0055107', 'GO:0055110', 'GO:0055115', 'GO:0055121', 'GO:0055122', 'GO:0055127', 'GO:0060007', 'GO:0060062', 'GO:0060085', 'GO:0060094', 'GO:0060107', 'GO:0060108', 'GO:0060111', 'GO:0060151', 'GO:0060169', 'GO:0060175', 'GO:0060220', 'GO:0060332', 'GO:0060345', 'GO:0060353', 'GO:0060405', 'GO:0060407', 'GO:0060427', 'GO:0060448', 'GO:0060458', 'GO:0060459', 'GO:0060514', 'GO:0060516', 'GO:0060580', 'GO:0060582', 'GO:0060658', 'GO:0060668', 'GO:0060681', 'GO:0060683', 'GO:0060685', 'GO:0060690', 'GO:0060696', 'GO:0060700', 'GO:0060719', 'GO:0060735', 'GO:0060738', 'GO:0060751', 'GO:0060782', 'GO:0060783', 'GO:0060786', 'GO:0060802', 'GO:0060832', 'GO:0060838', 'GO:0060917', 'GO:0060981', 'GO:0060987', 'GO:0061114', 'GO:0061120', 'GO:0061137', 'GO:0061140', 'GO:0061189', 'GO:0061196', 'GO:0061321', 'GO:0061330', 'GO:0061365', 'GO:0061453', 'GO:0061472', 'GO:0061517', 'GO:0061547', 'GO:0061595', 'GO:0061603', 'GO:0061613', 'GO:0061657', 'GO:0061708', 'GO:0061736', 'GO:0061798', 'GO:0061799', 'GO:0061834', 'GO:0061835', 'GO:0061845', 'GO:0061846', 'GO:0061853', 'GO:0061875', 'GO:0061896', 'GO:0061897', 'GO:0061898', 'GO:0061899', 'GO:0061910', 'GO:0061913', 'GO:0061917', 'GO:0061945', 'GO:0062027', 'GO:0062028', 'GO:0062049', 'GO:0062050', 'GO:0062062', 'GO:0062070', 'GO:0062086', 'GO:0062116', 'GO:0062150', 'GO:0062180', 'GO:0062181', 'GO:0062185', 'GO:0062202', 'GO:0062203', 'GO:0062204', 'GO:0062205', 'GO:0062206', 'GO:0062207', 'GO:0062213', 'GO:0070013', 'GO:0070038', 'GO:0070127', 'GO:0070144', 'GO:0070146', 'GO:0070149', 'GO:0070150', 'GO:0070159', 'GO:0070186', 'GO:0070237', 'GO:0070247', 'GO:0070259', 'GO:0070260', 'GO:0070284', 'GO:0070303', 'GO:0070338', 'GO:0070350', 'GO:0070409', 'GO:0070421', 'GO:0070428', 'GO:0070446', 'GO:0070453', 'GO:0070479', 'GO:0070488', 'GO:0070560', 'GO:0070625', 'GO:0070636', 'GO:0070694', 'GO:0070701', 'GO:0070702', 'GO:0070703', 'GO:0070825', 'GO:0070826', 'GO:0070832', 'GO:0070889', 'GO:0070931', 'GO:0070963', 'GO:0070974', 'GO:0071171', 'GO:0071172', 'GO:0071254', 'GO:0071272', 'GO:0071362', 'GO:0071366', 'GO:0071384', 'GO:0071424', 'GO:0071448', 'GO:0071506', 'GO:0071584', 'GO:0071594', 'GO:0071812', 'GO:0071858', 'GO:0071861', 'GO:0071909', 'GO:0071914', 'GO:0071926', 'GO:0071929', 'GO:0071967', 'GO:0072077', 'GO:0072110', 'GO:0072118', 'GO:0072160', 'GO:0072163', 'GO:0072223', 'GO:0072224', 'GO:0072255', 'GO:0072262', 'GO:0072264', 'GO:0072275', 'GO:0072283', 'GO:0072285', 'GO:0072303', 'GO:0072356', 'GO:0072377', 'GO:0072417', 'GO:0072479', 'GO:0072493', 'GO:0072527', 'GO:0072529', 'GO:0072532', 'GO:0072544', 'GO:0072547', 'GO:0072548', 'GO:0072549', 'GO:0072550', 'GO:0072551', 'GO:0072552', 'GO:0072585', 'GO:0072597', 'GO:0072599', 'GO:0072663', 'GO:0072747', 'GO:0075137', 'GO:0075523', 'GO:0080004', 'GO:0080013', 'GO:0080015', 'GO:0080016', 'GO:0080017', 'GO:0080019', 'GO:0080028', 'GO:0080051', 'GO:0080065', 'GO:0080072', 'GO:0080073', 'GO:0080074', 'GO:0080075', 'GO:0080089', 'GO:0080118', 'GO:0080131', 'GO:0080133', 'GO:0080161', 'GO:0080162', 'GO:0080171', 'GO:0080172', 'GO:0086029', 'GO:0089702', 'GO:0089714', 'GO:0090052', 'GO:0090075', 'GO:0090096', 'GO:0090139', 'GO:0090174', 'GO:0090182', 'GO:0090228', 'GO:0090269', 'GO:0090287', 'GO:0090291', 'GO:0090318', 'GO:0090319', 'GO:0090321', 'GO:0090376', 'GO:0090431', 'GO:0090447', 'GO:0090474', 'GO:0090512', 'GO:0090514', 'GO:0090515', 'GO:0090516', 'GO:0090518', 'GO:0090564', 'GO:0090567', 'GO:0090577', 'GO:0090580', 'GO:0090581', 'GO:0090582', 'GO:0090586', 'GO:0090587', 'GO:0090592', 'GO:0090601', 'GO:0090673', 'GO:0090697', 'GO:0090706', 'GO:0090711', 'GO:0090725', 'GO:0090732', 'GO:0093001', 'GO:0097004', 'GO:0097007', 'GO:0097008', 'GO:0097052', 'GO:0097125', 'GO:0097140', 'GO:0097141', 'GO:0097161', 'GO:0097258', 'GO:0097259', 'GO:0097306', 'GO:0097328', 'GO:0097339', 'GO:0097341', 'GO:0097343', 'GO:0097370', 'GO:0097377', 'GO:0097379', 'GO:0097403', 'GO:0097456', 'GO:0097502', 'GO:0097507', 'GO:0097508', 'GO:0097509', 'GO:0097540', 'GO:0097582', 'GO:0097583', 'GO:0097584', 'GO:0097585', 'GO:0097586', 'GO:0097594', 'GO:0097619', 'GO:0097657', 'GO:0097698', 'GO:0097699', 'GO:0097707', 'GO:0097712', 'GO:0098002', 'GO:0098604', 'GO:0098680', 'GO:0098724', 'GO:0098760', 'GO:0098799', 'GO:0098926', 'GO:0098934', 'GO:0098998', 'GO:0099158', 'GO:0099163', 'GO:0099563', 'GO:0099571', 'GO:0099615', 'GO:0099620', 'GO:0099627', 'GO:0101018', 'GO:0102009', 'GO:0102031', 'GO:0102068', 'GO:0102140', 'GO:0102161', 'GO:0102168', 'GO:0102175', 'GO:0102313', 'GO:0102358', 'GO:0102432', 'GO:0102435', 'GO:0102439', 'GO:0102440', 'GO:0102441', 'GO:0102447', 'GO:0102448', 'GO:0102449', 'GO:0102450', 'GO:0102524', 'GO:0102597', 'GO:0102614', 'GO:0102626', 'GO:0102627', 'GO:0102628', 'GO:0102698', 'GO:0102700', 'GO:0102701', 'GO:0102703', 'GO:0102732', 'GO:0102810', 'GO:0102822', 'GO:0102877', 'GO:0102889', 'GO:0102903', 'GO:0102905', 'GO:0102913', 'GO:0102921', 'GO:0102922', 'GO:0102934', 'GO:0102965', 'GO:0103002', 'GO:0106061', 'GO:0106095', 'GO:0106096', 'GO:0106136', 'GO:0106142', 'GO:0106144', 'GO:0106146', 'GO:0106149', 'GO:0106220', 'GO:0106223', 'GO:0106238', 'GO:0106239', 'GO:0106243', 'GO:0106244', 'GO:0106251', 'GO:0106255', 'GO:0106264', 'GO:0106276', 'GO:0106288', 'GO:0106313', 'GO:0106371', 'GO:0106373', 'GO:0106376', 'GO:0106377', 'GO:0106378', 'GO:0106402', 'GO:0106432', 'GO:0106439', 'GO:0110013', 'GO:0110043', 'GO:0110101', 'GO:0110103', 'GO:0120042', 'GO:0120047', 'GO:0120092', 'GO:0120094', 'GO:0120134', 'GO:0120178', 'GO:0120179', 'GO:0120207', 'GO:0120234', 'GO:0120272', 'GO:0120282', 'GO:0120323', 'GO:0120503', 'GO:0120505', 'GO:0120506', 'GO:0120511', 'GO:0120512', 'GO:0120527', 'GO:0120537', 'GO:0140004', 'GO:0140035', 'GO:0140063', 'GO:0140064', 'GO:0140084', 'GO:0140123', 'GO:0140145', 'GO:0140161', 'GO:0140169', 'GO:0140221', 'GO:0140266', 'GO:0140290', 'GO:0140292', 'GO:0140303', 'GO:0140314', 'GO:0140337', 'GO:0140339', 'GO:0140340', 'GO:0140376', 'GO:0140381', 'GO:0140382', 'GO:0140405', 'GO:0140432', 'GO:0140482', 'GO:0140586', 'GO:0140615', 'GO:0140646', 'GO:0140692', 'GO:0140818', 'GO:0140823', 'GO:0140830', 'GO:0140831', 'GO:0140832', 'GO:0140853', 'GO:0140892', 'GO:0140893', 'GO:0140901', 'GO:0140902', 'GO:0140924', 'GO:0140926', 'GO:0140934', 'GO:0140981', 'GO:0140987', 'GO:0140988', 'GO:0140993', 'GO:0141084', 'GO:0141118', 'GO:0141119', 'GO:0141129', 'GO:0141135', 'GO:0141139', 'GO:0141140', 'GO:0141141', 'GO:0141150', 'GO:0141152', 'G

In [10]:
print("--- Codification results ---")
print(f"Label shape (Y_train): {Y_train_sparse.shape}")
print(f"Object type: {type(Y_train_sparse)}") 
# <class 'scipy.sparse.csr.csr_matrix'>
print(f"RAM used (aprox): {Y_train_sparse.data.nbytes / 1024**2:.2f} MB")

--- Codification results ---
Label shape (Y_train): (65754, 24373)
Object type: <class 'scipy.sparse._csr.csr_matrix'>
RAM used (aprox): 3.27 MB

In [11]:
# Save Y_train_sparse and Y_val_sparse
np.save(y_train_sparse_path, Y_train_sparse)
np.save(y_val_sparse_path, Y_val_sparse)

# Save classes.npy (used later)

In [12]:
from tqdm import tqdm

In [13]:
# We use a SET to automatically store only unique terms
unique_classes = set()

# Iterate row by row to save RAM
for row in tqdm(df_train['go_terms']):
    terms = safe_eval_and_flatten(row)
    unique_classes.update(terms)

100%|██████████| 65754/65754 [00:02<00:00, 26473.53it/s]

In [14]:
sorted_classes = sorted(list(unique_classes))
classes_array = np.array(sorted_classes)

print(f"Number of unique GO terms in training set: {len(sorted_classes)}")

Number of unique GO terms in training set: 24373

In [15]:
num_cols_matrix = Y_train_sparse.shape[1]
    
if len(classes_array) == num_cols_matrix:
    print("OK! The number of classes matches the trained matrix.")
    
    # Save so we don't need to repeat this ever again
    np.save(classes_path, classes_array)
    print(f"File saved to: {output_path}classes.npy")
else:
    print(f"WARNING: Size mismatch.")
    print(f"Unique terms found in CSV: {len(classes_array)}")
    print(f"Columns in sparse matrix: {num_cols_matrix}")
    print("Check if data filtering was identical.")

OK! The number of classes matches the trained matrix.
File saved to: ../input/classes.npy

# Save IA_weights (used on validation)

In [16]:
df_weights = pd.read_csv(ia_weights_path, sep="\t", names=["go_terms", "ia"])
df_weights.head()

     go_terms        ia
0  GO:0000001  0.000000
1  GO:0000002  2.849666
2  GO:0000011  0.137504
3  GO:0000012  6.038630
4  GO:0000017  0.514573

In [17]:
ia_score_map = df_weights.set_index('go_terms')['ia'].to_dict()

In [18]:
MIN_IA_SCORE = 0.0

In [19]:
LABEL_COUNT = len(mlb.classes_)
LABEL_COUNT

24373

In [20]:
ia_weights_ordered = np.zeros(LABEL_COUNT, dtype=np.float32)

In [21]:
for i, go_term in enumerate(mlb.classes_):
    weight = ia_score_map.get(go_term, MIN_IA_SCORE)
    ia_weights_ordered[i] = weight

In [22]:
ia_weights_ordered.shape

(24373,)

In [23]:
np.save(final_ia_weights_path, ia_weights_ordered)